@baseUrl = http://localhost:3000/v1

###ROUTE GET pour tous les modèles
@name = spents
GET {{baseUrl}}/{{name}}

###ROUTE POST
POST {{baseUrl}}/{{name}}
Content-Type: application/json

{
    "label":"toto"
}

###ROUTE PATCH
PATCH {{baseUrl}}/{{name}}
Content-Type: application/json

{
    "id": 2,
    "intern_ref": "spent-demo2",
    "label": "facture edf",
    "amount": 236.95,
    "date": "2021-06-22T18:47:10.676Z",
    "member_id": 2,
    "category_id": 3
  }

### DELETE
DELETE {{baseUrl}}/category/6
